name: Fully Automated Luxury Fision

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.3
      with:
        nim-version: "stable"

    - name: Compile
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nim c fision.nim

    - uses: stefanzweifel/git-auto-commit-action@v4.1.3
      with:
        commit_message: Fully Automated Luxury Fision
        file_pattern: "*.nimble"
        commit_user_name: juancarlospaco
        commit_author: Juan Carlos
        branch: master
        commit_options: "--no-verify"
